server:
  port: 3355
  
spring:
  application:
    name: microcloud-config
  rabbitmq:         #现在将集成rabbitMQ作为消息服务总线      http://localhost:15672/
    host: mybroker.com #rabbitMQ主机服务地址
    port: 5672  #端口
    username: mxd
    password: password
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mxd888/microcloud-conf.git #为公共仓库，如果某些信息找不到了就是用他
          
                #变成：http://localhost:8888/actuator/bus-refresh
                #curl -X POST http://localhost:3355/actuator/bus-refresh
management:     #注意：config-server和config-client的配置都得加上  
  endpoints: 
    web:
      exposure:
        include: bus-refresh           
          
eureka: 
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true